### Get health status
GET http://localhost:5000/health
Accept: application/json

### Get all drinks
GET http://localhost:5000/drinks
Accept: application/json

### Get drink by id
GET http://localhost:5000/drinks/1
Accept: application/json

### Create one or more drinks (Beer, Wine, Vodka)
POST http://localhost:5000/drinks
Content-Type: application/json

[
    {
  "name": "Good wine",
  "alcoholContent": 12.3,
  "type": 1,
  "wineType": 3,
    "year": 2018,
  "vineyard": "North Vineyard"
}
]

### Update a drink
PUT http://localhost:5000/drinks/1
Content-Type: application/json
{
    "id": 1,
    "name": "Updated Beer",
    "type": 0, // 0 = AlcoholType.Beer
    "alcoholContent": 6.0,
    "brewery": "Updated Brewery",
    "beerType": 1 // 1 = BeerType.Ale
}

### Delete a drink
DELETE http://localhost:5000/drinks/1

### Create a rating
POST http://localhost:5000/ratings
Content-Type: application/json
{
    "score": 5,
    "drinkId": 1
}

### Get all ratings for a drink
GET http://localhost:5000/ratings/1
Accept: application/json

### Get average rating for a drink
GET http://localhost:5000/ratings/1/average
Accept: application/json
