// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using RateDrinksApi.Data;
using RateDrinksApi.Models.Compiled;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(DrinksDbContext), typeof(DrinksDbContextModel))]
