// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace RateDrinksApi.Models.Compiled
{
    public partial class DrinksDbContextModel
    {
        private DrinksDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("ff259a2b-80b2-4e51-a08d-e7fe91cf8335"), entityTypeCount: 4)
        {
        }

        partial void Initialize()
        {
            var drinkRecord = DrinkRecordEntityType.Create(this);
            var rating = RatingEntityType.Create(this);
            var testUser = TestUserEntityType.Create(this);
            var user = UserEntityType.Create(this);

            RatingEntityType.CreateForeignKey1(rating, drinkRecord);

            DrinkRecordEntityType.CreateAnnotations(drinkRecord);
            RatingEntityType.CreateAnnotations(rating);
            TestUserEntityType.CreateAnnotations(testUser);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.2");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
